### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by clofresh** [bartbes/lovelybigplanet#1]
Hi, I get a black screen when I try running the 1.0PublicBeta tagged version. However, the PublicAlpha0.1 works for me. I'm running löve 0.5.0 on Mac OS X 10.6.1.

**Comment by TheLinx** [comment]
You need the Löve 0.6.0 alpha - get it from [the builds page](http://love2d.org/builds/) (pre-packaged, mac packs out of date) or [the mercurial repo](http://love.hg.sourceforge.net/hgweb/love/love/) (you'll need to build it yourself)

**Comment by bartbes** [comment]
I can only say TheLinx is right, time to close the issue.
