### ISSUE TITLE
not start with löve 0.8

### ISSUE THREAD

**Issue by MarkusHackspacher** [bartbes/lovelybigplanet#2]
$ love lovelybigplanet/
Error: main.lua:1: attempt to compare string with number
stack traceback:
        main.lua:1: in main chunk
        [C]: in function 'require'
        [string "boot.lua"]:331: in function <[string "boot.lua"]:227>
        [C]: in function 'xpcall'

$ love --version
LOVE 0.8.0 (Rubber Piggy)

OS: Debian 7

**Comment by gvx** [comment]
This project is super old. We transitioned from 0.5.0 to 0.6.0 during development, that old! It's no longer developed in any way.
